Encrypting the home dir. Setting up init scripts to activate profile. Removing a lot of junk. Organizing data.

diff --git a/markizano/home/markizano/bin/unsvn b/markizano/home/markizano/bin/unsvn
--- a/markizano/home/markizano/bin/unsvn
+++ b/markizano/home/markizano/bin/unsvn
@@ -6,14 +6,19 @@ function _unsvn(){
 }
 
 if [ -z "$1" ]; then
-	target="$(pwd)";
+	target="$PWD";
 else
+	if echo $1 | grep -Piq '\x2D\x2D?h(elp)?'; then
+		echo "Usage: $0 [file]";
+		exit 8;
+	fi
+
 	if [ ! -d "$1" ]; then
 		echo "$(basename "$0"): cannot stat \`$1'. No such directory." 1>&2;
 	fi
+
 	target="$1";
 fi
 
-echo -e "Are you sure you want to unsvn ${target}?";
-read confirm;
-echo $confirm | grep -iP 'y(es)?' >/dev/null && _unsvn $target || echo Abort.;
+read -p "Are you sure you want to unsvn ${target}?" confirm;
+echo $confirm | grep -iPq 'y(es)?' && _unsvn "$target" || echo Abort.;
